---
- hosts: all
  become: yes
  vars:
    user: vagrant
  tasks:
  - name: Install dependecies
    apt:
      name: 
      - ca-certificates 
      - curl
      - gnupg
      - lsb-release
      - apt-transport-https
      state: latest
      update_cache: yes
  - name: define arch variable
    command: dpkg --print-architecture
    register: arch
  - name: define release variable  
    command: lsb_release -cs
    register: release 
  - name: add GPG key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  - name: add stable repository 
    apt_repository:
      repo: deb [arch={{arch.stdout}} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian  {{release.stdout}} stable
      filename: docker
      update_cache: yes
  - name: Install docker engine
    apt:
      name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      state: latest
  - name: add GPG key
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      keyring: /usr/share/keyrings/kubernetes-archive-keyring.gpg
  - name: add stable repository 
    apt_repository:
      repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
      filename: kubernetes
      update_cache: yes
  - name: Install zsh shell and kubectl
    apt: 
      name: 
      - zsh
      - kubectl
      state: latest
  - name: add user to docker group
    user:
      user: '{{user}}'
      append: yes 
      groups:
      - docker
      shell: /bin/zsh
  - name: Verify K3D installation
    stat:
      path: /usr/local/bin/k3d
    register: k3d
  - name: Install k3d and start cluster
    block:
    - name: install K3D
      shell: curl -s https://raw.githubusercontent.com/rancher/k3d/main/install.sh | bash
    - name: Create Cluster
      command: k3d cluster create --config /home/{{user}}/Documents/workspace/k3d/one_master_3_workers.yml
      become_user: '{{user}}'
    when: not k3d.stat.exists

